language: node_js
node_js:
  - "8"
os:
  - windows
  - linux
  - osx
install:
  - npm ci
script:
  - npm run test
  - npx codecov
cache:
  directories:
    - "$HOME/.npm"
branches:
  only:
    - master
